<?php
return array(
	'display'=>array(
		'title'=>'是否显示:',
		'type'=>'radio',
		'options'=>array(
			'1'=>'显示',
			'0'=>'不显示'
		),
		'value'=>'1'
	),
	'showCloseButton'=>array(
		'title'=>'是否显示关闭按钮',
		'type'=>'radio',
		'options'=>array(
			'true'=>'显示',
			'false'=>'不显示'
		),
		'value'=>'true'
	),
	'showNavArrows'=>array(
		'title'=>'显示上一张下一张导航箭头',
		'type'=>'radio',
		'options'=>array(
			'true'=>'显示',
			'false'=>'不显示'
		),
		'value'=>'true'
	),
	'enableEscapeButton'=>array(
		'title'=>'启用ESC来关闭fancybox',
		'type'=>'radio',
		'options'=>array(
			'true'=>'启用',
			'false'=>'不启用'
		),
		'value'=>'true'
	),
	'padding'=>array(
		'title'=>'浏览框内边距',
		'type'=>'text',
		'value'=>'0',
	),
	'margin'=>array(
		'title'=>'浏览框外边距',
		'type'=>'text',
		'value'=>'0',
	),
	'opacity'=>array(
		'title'=>'动画透明度是否改变',
		'type'=>'radio',
		'options'=>array(
			'true'=>'开启',
			'false'=>'关闭',
		),
		'value'=>'false',
	),
	'cyclic'=>array(
		'title'=>'相册循环播放:',
		'type'=>'radio',
		'options'=>array(
			'true'=>'开启',
			'false'=>'关闭',
		),
		'value'=>'false',
	),
	'scrolling'=>array(
		'title'=>'创建或隐藏滚动条',
		'type'=>'radio',
		'options'=>array(
			'true'=>'开启',
			'false'=>'关闭',
			'auto'=>'自动'
		),
		'value'=>'auto',
	),
	'width'=>array(
		'title'=>'iframe和swf的宽度:',
		'tip'  =>'autoDimensions为false，这也可以设置普通文本的宽度',
		'type' =>'text',
		'value'=>'560',
	),
	'height'=>array(
		'title'=>'iframe和swf的宽度:',
		'tip'  =>'autoDimensions为false，这也可以设置普通文本的高度',
		'type' =>'text',
		'value'=>'340',
	),
	'autoScale'=>array(
		'title'=>'自适应浏览器窗口大小',
		'tip'  =>'如果为true，fancybox可以自适应浏览器窗口大小',
		'type'=>'radio',
		'options'=>array(
			'true'=>'开启',
			'false'=>'关闭',
		),
		'value'=>'true',
	),
	'autoDimensions'=>array(
		'title'=>'在内联文本和ajax中，设置是否动态调整元素的尺寸(autoDimensions)',
		'tip'  =>'如果为true，请确保你已经为元素设置了尺寸大小',
		'type'=>'radio',
		'options'=>array(
			'true'=>'开启',
			'false'=>'关闭',
		),
		'value'=>'true',
	),
	'centerOnScroll'=>array(
		'title'=>'fancybox是否停留在浏览器中心',
		'type'=>'radio',
		'options'=>array(
			'true'=>'开启',
			'false'=>'关闭',
		),
		'value'=>'false',
	),
	'hideOnContentClick'=>array(
		'title'=>'是否点击图片关闭',
		'type'=>'radio',
		'options'=>array(
			'true'=>'是',
			'false'=>'否',
		),
		'value'=>'false',
	),
	'hideOnOverlayClick'=>array(
		'title'=>'是否点击遮罩关闭',
		'type'=>'radio',
		'options'=>array(
			'true'=>'是',
			'false'=>'否',
		),
		'value'=>'true',
	),
	'overlayShow'=>array(
		'title'=>'是否显示遮罩',
		'type'=>'radio',
		'options'=>array(
			'true'=>'是',
			'false'=>'否',
		),
		'value'=>'true',
	),
	'overlayOpacity'=>array(
		'title'=>'遮罩透明度',
		'tip'=>'遮罩层的透明度（范围0-1）',
		'type'=>'text',
		'value'=>'0.3',
	),
	'overlayColor'=>array(
		'title'=>'遮罩层的背景颜色',
		'tip'=>'例如：#666',
		'type'=>'text',
		'value'=>'#666',
	),
	'titleShow'=>array(
		'title'=>'是否显示标题',
		'type'=>'radio',
		'options'=>array(
			'true'=>'是',
			'false'=>'否',
		),
		'value'=>'true',
	),
	'titlePosition'=>array(
		'title'=>'标题显示的位置',
		'tip'=>'设置标题显示的位置.可以设置成 outside,inside或over',
		'type'=>'radio',
		'options'=>array(
			'outside'=>'outside',
			'inside'=>'inside',
			'over'=>'over'
		),
		'value'=>'outside',
	),
	'transitionIn'=>array(
		'title'=>'动画进入效果:',
		'type'=>'radio',		 
		'options'=>array(
			'elastic'=>'弹性弹出',
			'fade'=>'渐变的',
			'none'=>'没有效果',
		),
		'value'=>'fade',
	),
	'transitionOut'=>array(
		'title'=>'动画消失效果:',
		'type'=>'radio',
		'options'=>array(
			'elastic'=>'弹性弹出',
			'fade'=>'渐变的',
			'none'=>'没有效果',
		),
		'value'=>'fade',
	),
	'speedIn'=>array(
		'title'=>'动画进入时的时间间隔',
		'tip'=>'fade和 elastic 动画切换的时间间隔, 以毫秒为单位',
		'type'=>'text',
		'value'=>'300',
	),
	'speedOut'=>array(
		'title'=>'动画消失时的时间间隔',
		'tip'=>'fade和 elastic 动画切换的时间间隔, 以毫秒为单位',
		'type'=>'text',
		'value'=>'300',
	),
	'changeSpeed'=>array(
		'title'=>'动画消失时的时间间隔',
		'tip'=>'切换时fancybox尺寸的变化时间间隔（即变化的速度），以毫秒为单位',
		'type'=>'text',
		'value'=>'300',
	),
	
	'easingIn'=>array(
		'title'=>'为elastic设置动画属性(进入时)',
		'type'=>'select',
		'options'=>array(
			'linear'=>'linear',		 
			'swing'=>'swing',
			'jswing'=>'jswing',		
			'easeInQuad'=>'easeInQuad',
			'easeOutQuad'=>'easeOutQuad',		
			'easeInOutQuad'=>'easeInOutQuad',
			'easeInCubic'=>'easeInCubic',		 
			'easeOutCubic'=>'easeOutCubic',
			'easeInOutCubic'=>'easeInOutCubic',		 
			'easeInQuart'=>'easeInQuart',
			'easeOutQuart'=>'easeOutQuart',		
			'easeInOutQuart'=>'easeInOutQuart',
			'easeInQuint'=>'easeInQuint',		
			'easeOutQuint'=>'easeOutQuint',
			'easeInOutQuint'=>'easeInOutQuint',		 
			'easeInSine'=>'easeInSine',
			'easeOutSine'=>'easeOutSine',		 
			'easeInOutSine'=>'easeInOutSine',
			'easeInExpo'=>'easeInExpo',		
			'easeOutExpo'=>'easeOutExpo',
			'easeInOutExpo'=>'easeInOutExpo',		
			'easeInCirc'=>'easeInCirc',
			'easeOutCirc'=>'easeOutCirc',		 
			'easeInOutCirc'=>'easeInOutCirc',
			'easeInElastic'=>'easeInElastic',		 
			'easeOutElastic'=>'easeOutElastic',
			'easeInOutElastic'=>'easeInOutElastic',		
			'easeInBack'=>'easeInBack',
			'easeOutBack'=>'easeOutBack',		
			'easeInOutBack'=>'easeInOutBack',
			'easeInBounce'=>'easeInBounce',		 
			'easeOutBounce'=>'easeOutBounce',
			'easeInOutBounce'=>'easeInOutBounce'
		),
		'value'=>'easeInCubic',
	),
	'easingOut'=>array(
		'title'=>'为elastic设置动画属性(消失时)',
		'type'=>'select',		 
		'options'=>array(
			'linear'=>'linear',		 
			'swing'=>'swing',
			'jswing'=>'jswing',		
			'easeInQuad'=>'easeInQuad',
			'easeOutQuad'=>'easeOutQuad',		
			'easeInOutQuad'=>'easeInOutQuad',
			'easeInCubic'=>'easeInCubic',		 
			'easeOutCubic'=>'easeOutCubic',
			'easeInOutCubic'=>'easeInOutCubic',		 
			'easeInQuart'=>'easeInQuart',
			'easeOutQuart'=>'easeOutQuart',		
			'easeInOutQuart'=>'easeInOutQuart',
			'easeInQuint'=>'easeInQuint',		
			'easeOutQuint'=>'easeOutQuint',
			'easeInOutQuint'=>'easeInOutQuint',		 
			'easeInSine'=>'easeInSine',
			'easeOutSine'=>'easeOutSine',		 
			'easeInOutSine'=>'easeInOutSine',
			'easeInExpo'=>'easeInExpo',		
			'easeOutExpo'=>'easeOutExpo',
			'easeInOutExpo'=>'easeInOutExpo',		
			'easeInCirc'=>'easeInCirc',
			'easeOutCirc'=>'easeOutCirc',		 
			'easeInOutCirc'=>'easeInOutCirc',
			'easeInElastic'=>'easeInElastic',		 
			'easeOutElastic'=>'easeOutElastic',
			'easeInOutElastic'=>'easeInOutElastic',		
			'easeInBack'=>'easeInBack',
			'easeOutBack'=>'easeOutBack',		
			'easeInOutBack'=>'easeInOutBack',
			'easeInBounce'=>'easeInBounce',		 
			'easeOutBounce'=>'easeOutBounce',
			'easeInOutBounce'=>'easeInOutBounce'
		),
		'value'=>'easeOutCubic',
	)
);
